module.exports = {
  initialValues: {
    nftId: 'bayc-1',
    sellerId: 'jvdm5-xkwgc-4t2x7-ojmjd-ail2p-6agif-7m6a6-z6eok-oxueq-inzfb-zae',
    priceOffer: '0.03',
  },
  nft: {
    metadata: {
      Class: [
        {
          value: {
            Principal: {
              _arr: {
                0: 86,
                1: 48,
                2: 185,
                3: 61,
                4: 95,
                5: 238,
                6: 75,
                7: 18,
                8: 48,
                9: 33,
                10: 122,
                11: 127,
                12: 128,
                13: 100,
                14: 23,
                15: 236,
                16: 240,
                17: 61,
                18: 159,
                19: 17,
                20: 202,
                21: 117,
                22: 232,
                23: 72,
                24: 33,
                25: 185,
                26: 40,
                27: 114,
                28: 2,
              },
              toText: function () {
                return 'jvdm5-xkwgc-4t2x7-ojmjd-ail2p-6agif-7m6a6-z6eok-oxueq-inzfb-zae';
              },
              _isPrincipal: true,
            },
          },
          name: 'owner',
          immutable: false,
        },
        {
          value: { Text: 'com.bayc.ape.1.primary' },
          name: 'preview_asset',
          immutable: true,
        },
        { value: { Text: 'com.bayc.ape.hidden' }, name: 'hidden_asset', immutable: true },
        {
          value: { Text: 'com.bayc.ape.1.primary' },
          name: 'primary_asset',
          immutable: true,
        },
        {
          value: { Text: 'com.bayc.ape.1.html' },
          name: 'experience_asset',
          immutable: true,
        },
        { value: { Text: 'bayc-1' }, name: 'id', immutable: true },
        { value: { Bool: false }, name: 'is_soulbound', immutable: false },
        {
          value: {
            Class: [
              {
                value: {
                  Text: '1d29aad9618051b971acd5b01fb9be47287b72ffa740982077ae4cea0f21c926',
                },
                name: 'current_sale_id',
                immutable: false,
              },
              { value: { Text: 'minted' }, name: 'status', immutable: false },
            ],
          },
          name: '__system',
          immutable: false,
        },
        {
          value: {
            Array: {
              thawed: [
                {
                  Class: [
                    {
                      value: { Text: 'com.bayc.ape.1.primary' },
                      name: 'library_id',
                      immutable: true,
                    },
                    { value: { Text: 'BAYC - Ape 1' }, name: 'title', immutable: true },
                    { value: { Text: 'canister' }, name: 'location_type', immutable: true },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/com.bayc.ape.1.primary',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'image/png' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 500000 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    {
                      value: { Text: 'com.bayc.ape.hidden' },
                      name: 'library_id',
                      immutable: true,
                    },
                    { value: { Text: 'Random-Ape' }, name: 'title', immutable: true },
                    { value: { Text: 'web' }, name: 'location_type', immutable: true },
                    {
                      value: { Text: 'https://ik.imagekit.io/bayc/assets/mystery-ape.gif' },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'image/gif' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 500000 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    {
                      value: { Text: 'com.bayc.ape.hidden2' },
                      name: 'library_id',
                      immutable: true,
                    },
                    { value: { Text: 'Random-Ape' }, name: 'title', immutable: true },
                    {
                      value: { Text: 'collection' },
                      name: 'location_type',
                      immutable: true,
                    },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/com.bayc.ape.1.hidden2',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'image/gif' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 500000 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    {
                      value: { Text: 'com.bayc.ape.1.html' },
                      name: 'library_id',
                      immutable: true,
                    },
                    { value: { Text: 'BAYC Sample' }, name: 'title', immutable: true },
                    { value: { Text: 'canister' }, name: 'location_type', immutable: true },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/com.bayc.ape.1.html',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'text/html' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 500000 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    { value: { Text: 'vault' }, name: 'library_id', immutable: true },
                    { value: { Text: 'vault dApp' }, name: 'title', immutable: true },
                    {
                      value: { Text: 'collection' },
                      name: 'location_type',
                      immutable: true,
                    },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/vault',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'text/html' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 1503756 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    { value: { Text: 'ledger' }, name: 'library_id', immutable: true },
                    { value: { Text: 'Ledger dApp' }, name: 'title', immutable: true },
                    {
                      value: { Text: 'collection' },
                      name: 'location_type',
                      immutable: true,
                    },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/ledger',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'text/html' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 974320 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    { value: { Text: 'data' }, name: 'library_id', immutable: true },
                    { value: { Text: 'Data dApp' }, name: 'title', immutable: true },
                    {
                      value: { Text: 'collection' },
                      name: 'location_type',
                      immutable: true,
                    },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/data',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'text/html' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 936231 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
                {
                  Class: [
                    { value: { Text: 'marketplace' }, name: 'library_id', immutable: true },
                    { value: { Text: 'Marketplace DApp' }, name: 'title', immutable: true },
                    {
                      value: { Text: 'collection' },
                      name: 'location_type',
                      immutable: true,
                    },
                    {
                      value: {
                        Text: 'https://frfol-iqaaa-aaaaj-acogq-cai.raw.ic0.app/-/bayc-01/-/marketplace',
                      },
                      name: 'location',
                      immutable: true,
                    },
                    { value: { Text: 'text/html' }, name: 'content_type', immutable: true },
                    { value: { Text: '1' }, name: 'content_hash', immutable: true },
                    { value: { Nat: 1492130 }, name: 'size', immutable: true },
                    { value: { Text: '1' }, name: 'sort', immutable: true },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                  ],
                },
              ],
            },
          },
          name: 'library',
          immutable: false,
        },
        {
          value: {
            Array: {
              thawed: [
                {
                  Class: [
                    {
                      value: { Text: 'com.bayc.sample.app' },
                      name: 'app_id',
                      immutable: true,
                    },
                    { value: { Text: 'public' }, name: 'read', immutable: false },
                    {
                      value: {
                        Class: [
                          { value: { Text: 'allow' }, name: 'type', immutable: false },
                          {
                            value: {
                              Array: {
                                thawed: [
                                  {
                                    Principal: {
                                      _arr: {
                                        0: 99,
                                        1: 45,
                                        2: 107,
                                        3: 50,
                                        4: 96,
                                        5: 213,
                                        6: 232,
                                        7: 12,
                                        8: 185,
                                        9: 188,
                                        10: 209,
                                        11: 103,
                                        12: 182,
                                        13: 254,
                                        14: 98,
                                        15: 125,
                                        16: 107,
                                        17: 24,
                                        18: 100,
                                        19: 125,
                                        20: 171,
                                        21: 119,
                                        22: 245,
                                        23: 154,
                                        24: 36,
                                        25: 123,
                                        26: 144,
                                        27: 191,
                                        28: 2,
                                      },
                                      _isPrincipal: true,
                                    },
                                  },
                                ],
                              },
                            },
                            name: 'list',
                            immutable: false,
                          },
                        ],
                      },
                      name: 'write',
                      immutable: false,
                    },
                    {
                      value: {
                        Class: [
                          { value: { Text: 'allow' }, name: 'type', immutable: false },
                          {
                            value: {
                              Array: {
                                thawed: [
                                  {
                                    Principal: {
                                      _arr: {
                                        0: 99,
                                        1: 45,
                                        2: 107,
                                        3: 50,
                                        4: 96,
                                        5: 213,
                                        6: 232,
                                        7: 12,
                                        8: 185,
                                        9: 188,
                                        10: 209,
                                        11: 103,
                                        12: 182,
                                        13: 254,
                                        14: 98,
                                        15: 125,
                                        16: 107,
                                        17: 24,
                                        18: 100,
                                        19: 125,
                                        20: 171,
                                        21: 119,
                                        22: 245,
                                        23: 154,
                                        24: 36,
                                        25: 123,
                                        26: 144,
                                        27: 191,
                                        28: 2,
                                      },
                                      _isPrincipal: true,
                                    },
                                  },
                                ],
                              },
                            },
                            name: 'list',
                            immutable: false,
                          },
                        ],
                      },
                      name: 'permissions',
                      immutable: false,
                    },
                    {
                      value: {
                        Class: [
                          {
                            value: { Text: 'Ape 1' },
                            name: 'com.bayc.sample.app.name',
                            immutable: false,
                          },
                          {
                            value: { Nat: 16 },
                            name: 'com.bayc.sample.app.total_in_collection',
                            immutable: false,
                          },
                          {
                            value: { Text: 'BAYC' },
                            name: 'com.bayc.sample.app.creator_name',
                            immutable: false,
                          },
                          {
                            value: {
                              Principal: {
                                _arr: {
                                  0: 99,
                                  1: 45,
                                  2: 107,
                                  3: 50,
                                  4: 96,
                                  5: 213,
                                  6: 232,
                                  7: 12,
                                  8: 185,
                                  9: 188,
                                  10: 209,
                                  11: 103,
                                  12: 182,
                                  13: 254,
                                  14: 98,
                                  15: 125,
                                  16: 107,
                                  17: 24,
                                  18: 100,
                                  19: 125,
                                  20: 171,
                                  21: 119,
                                  22: 245,
                                  23: 154,
                                  24: 36,
                                  25: 123,
                                  26: 144,
                                  27: 191,
                                  28: 2,
                                },
                                _isPrincipal: true,
                              },
                            },
                            name: 'com.bayc.sample.app.creator_principal',
                            immutable: false,
                          },
                        ],
                      },
                      name: 'data',
                      immutable: false,
                    },
                  ],
                },
              ],
            },
          },
          name: '__apps',
          immutable: false,
        },
      ],
    },
    current_sale: [
      {
        token_id: 'bayc-1',
        sale_type: {
          auction: {
            status: { open: null },
            participants: [
              [
                {
                  _arr: {
                    0: 86,
                    1: 48,
                    2: 185,
                    3: 61,
                    4: 95,
                    5: 238,
                    6: 75,
                    7: 18,
                    8: 48,
                    9: 33,
                    10: 122,
                    11: 127,
                    12: 128,
                    13: 100,
                    14: 23,
                    15: 236,
                    16: 240,
                    17: 61,
                    18: 159,
                    19: 17,
                    20: 202,
                    21: 117,
                    22: 232,
                    23: 72,
                    24: 33,
                    25: 185,
                    26: 40,
                    27: 114,
                    28: 2,
                  },
                  _isPrincipal: true,
                },
                1659533850081061680,
              ],
            ],
            current_bid_amount: 2000000,
            winner: [],
            end_date: 1660219980000000000,
            wait_for_quiet_count: [0],
            current_escrow: [
              {
                token: {
                  ic: {
                    fee: 200000,
                    decimals: 8,
                    canister: {
                      _arr: {
                        0: 0,
                        1: 0,
                        2: 0,
                        3: 0,
                        4: 1,
                        5: 32,
                        6: 0,
                        7: 185,
                        8: 1,
                        9: 1,
                      },
                      _isPrincipal: true,
                    },
                    standard: { Ledger: null },
                    symbol: 'OGY',
                  },
                },
                token_id: 'bayc-1',
                seller: {
                  principal: {
                    _arr: {
                      0: 86,
                      1: 48,
                      2: 185,
                      3: 61,
                      4: 95,
                      5: 238,
                      6: 75,
                      7: 18,
                      8: 48,
                      9: 33,
                      10: 122,
                      11: 127,
                      12: 128,
                      13: 100,
                      14: 23,
                      15: 236,
                      16: 240,
                      17: 61,
                      18: 159,
                      19: 17,
                      20: 202,
                      21: 117,
                      22: 232,
                      23: 72,
                      24: 33,
                      25: 185,
                      26: 40,
                      27: 114,
                      28: 2,
                    },
                    _isPrincipal: true,
                  },
                },
                buyer: {
                  principal: {
                    _arr: {
                      0: 86,
                      1: 48,
                      2: 185,
                      3: 61,
                      4: 95,
                      5: 238,
                      6: 75,
                      7: 18,
                      8: 48,
                      9: 33,
                      10: 122,
                      11: 127,
                      12: 128,
                      13: 100,
                      14: 23,
                      15: 236,
                      16: 240,
                      17: 61,
                      18: 159,
                      19: 17,
                      20: 202,
                      21: 117,
                      22: 232,
                      23: 72,
                      24: 33,
                      25: 185,
                      26: 40,
                      27: 114,
                      28: 2,
                    },
                    _isPrincipal: true,
                  },
                },
                amount: 2000000,
              },
            ],
            allow_list: [],
            min_next_bid: 3000000,
            config: {
              auction: {
                start_price: 1000000,
                token: {
                  ic: {
                    fee: 200000,
                    decimals: 8,
                    canister: {
                      _arr: {
                        0: 0,
                        1: 0,
                        2: 0,
                        3: 0,
                        4: 1,
                        5: 32,
                        6: 0,
                        7: 185,
                        8: 1,
                        9: 1,
                      },
                      _isPrincipal: true,
                    },
                    standard: { Ledger: null },
                    symbol: 'OGY',
                  },
                },
                reserve: [],
                start_date: 1659533848982000000,
                min_increase: { amount: 1000000 },
                allow_list: [],
                buy_now: [100000000],
                ending: { date: 1660219980000000000 },
              },
            },
          },
        },
        sale_id: '1d29aad9618051b971acd5b01fb9be47287b72ffa740982077ae4cea0f21c926',
      },
    ],
  },
};
